import { parseAbi } from "viem";

/// AgentVouchEvm ABI for the gas-free flow plus clean-break base-v1-a1 tooling.
/// (USDC approve/balanceOf/decimals come from viem's built-in `erc20Abi`.)
export const agentVouchAbi = parseAbi([
  "function registerAgent(string metadataUri)",
  "function depositAuthorBond(uint256 amount)",
  "function vouch(address vouchee, uint256 stake)",
  "function createSkillListing(bytes32 skillIdHash, string uri, string name, string description, uint256 priceUsdcMicros) returns (bytes32)",
  "function updateSkillListing(bytes32 id, string uri, string name, string description, uint256 priceUsdcMicros) returns (uint64)",
  "function purchaseSkill(bytes32 id) returns (bytes32)",
  "function claimVoucherRevenue(address author)",
  "function withdrawAuthorProceeds(bytes32 id, uint64 revision, uint256 amount)",
  "function openPaidPurchaseReport(address author, bytes32 listingId, bytes32 purchaseId, string evidenceUri) returns (uint64)",
  "function reviewPaidPurchaseReport(uint64 reportId, bool accept)",
  "function resolvePaidPurchaseReport(uint64 reportId, uint8 ruling)",
  "function slashPaidPurchaseReportVouches(uint64 reportId, address[] vouchers)",
  "function claimPaidPurchaseReportCredit(uint64 reportId)",
  "function closePaidPurchaseReportCredit(uint64 reportId)",
  "function claimRestitutionReserve()",
  // x402 Lane B (trust-minimized): the agent signs an EIP-3009 authorization off-chain;
  // a relayer submits this and the contract pulls USDC + records the purchase atomically.
  "function purchaseWithAuthorization(bytes32 id, address buyer, uint256 validAfter, uint256 validBefore, uint8 v, bytes32 r, bytes32 s) returns (bytes32)",
  "function PROTOCOL_VERSION() view returns (string)",
  "function getConfig() view returns ((address usdc, string chainContext, uint256 minVouchStakeUsdcMicros, uint256 disputeBondUsdcMicros, uint256 minAuthorBondForFreeListingUsdcMicros, uint256 minPaidListingPriceUsdcMicros, uint16 authorShareBps, uint16 voucherShareBps, uint16 protocolFeeBps, uint8 slashPercentage, uint256 authorProceedsLockSeconds, uint256 refundClaimWindowSeconds, uint16 challengerRewardBps, uint256 challengerRewardCapUsdcMicros, uint32 stakeWeightPerUsdc, uint256 riskComponentCap, uint32 vouchWeight, uint256 vouchComponentCap, uint32 longevityBonusPerDay, uint256 longevityComponentCap, uint256 upheldDisputePenalty, uint256 reputationScoreCap, address treasuryRecipient))",
  "function getProfile(address agent) view returns ((bool registered, string metadataUri, uint256 reputationScore, uint64 totalVouchesReceived, uint64 totalVouchesGiven, uint256 totalVouchStakeReceivedUsdcMicros, uint256 authorBondUsdcMicros, uint64 activeFreeListingCount, uint64 openDisputes, uint64 upheldDisputes, uint64 dismissedDisputes, uint256 rewardIndexUsdcMicrosX1e12, uint256 unclaimedVoucherRevenueUsdcMicros, uint64 registeredAt, uint64 slashingReportCount, uint256 totalAuthorBondSlashedUsdcMicros, uint256 totalVouchStakeSlashedUsdcMicros))",
  "function getVouch(address voucher, address vouchee) view returns ((address voucher, address vouchee, uint256 stakeUsdcMicros, uint8 status, uint256 cumulativeRevenueUsdcMicros, uint64 linkedListingCount, uint256 entryRewardIndexUsdcMicrosX1e12, uint256 pendingRewardsUsdcMicros, uint64 lastPayoutAt))",
  "function getListing(bytes32 id) view returns ((address author, bytes32 skillIdHash, string uri, string name, string description, uint256 priceUsdcMicros, uint64 currentRevision, uint256 totalDownloads, uint256 totalRevenueUsdcMicros, uint8 status, bool lockedByDispute, bool exists))",
  "function getSettlement(bytes32 id, uint64 revision) view returns ((bool initialized, uint64 createdAt, uint64 updatedAt, uint256 authorProceedsUsdcMicros, uint256 slashedDepositUsdcMicros, bool locked))",
  "function getPurchase(bytes32 purchaseId) view returns ((bool exists, address buyer, bytes32 listingId, uint64 revision, uint256 priceUsdcMicros, uint256 authorShareUsdcMicros, uint256 voucherPoolUsdcMicros, uint64 timestamp, uint8 lane))",
  "function getPaidPurchaseReportCore(uint64 reportId) view returns (address buyer, address author, bytes32 listingId, bytes32 purchaseId, uint64 filedAt, uint64 reviewDeadline, uint64 acceptedAt, uint64 terminalAt, uint8 status, uint8 outcome)",
  "function getPaidPurchaseReportSettlement(uint64 reportId) view returns (uint8 slashPercentage, uint256 activeVouchStake, uint256 processedPreSlashStake, uint256 authorBondSlash, uint256 voucherSlash, uint256 buyerEntitlement, uint256 buyerCredit, uint64 claimDeadline, bool creditHandled)",
  "function getPaidPurchaseReportEvidence(uint64 reportId) view returns (string)",
  "event Vouched(address indexed voucher, address indexed vouchee, uint256 stake)",
  "event VouchRevoked(address indexed voucher, address indexed vouchee, uint256 returned)",
  "event SkillListingUpdated(bytes32 indexed listingId, address indexed author, uint64 revision, uint256 price, bool free, bool revisionChanged)",
  "event PaidPurchaseReportOpened(uint64 indexed reportId, address indexed buyer, address indexed author, bytes32 listingId, bytes32 purchaseId, uint256 bond, uint64 reviewDeadline, string evidenceUri)",
  "event PaidPurchaseReportAccepted(uint64 indexed reportId, address indexed resolver, address indexed author, uint64 acceptedAt)",
  "event PaidPurchaseReportRejected(uint64 indexed reportId, address indexed resolver, address indexed buyer, uint256 reserveCredit, uint64 buyerCooldownUntil)",
  "event PaidPurchaseReportExpired(uint64 indexed reportId, address indexed buyer, address indexed author, uint256 buyerCredit, uint64 claimDeadline, uint64 authorCooldownUntil)",
  "event PaidPurchaseReportParked(uint64 indexed reportId, address indexed resolver, address indexed author, uint8 slashPercentage, uint256 activeVouchStake, uint256 authorBondSlash)",
  "event PaidPurchaseReportVouchSlashed(uint64 indexed reportId, address indexed voucher, uint256 preSlashStake, uint256 slashAmount, uint256 processedPreSlashStake)",
  "event PaidPurchaseReportDismissed(uint64 indexed reportId, address indexed resolver, address indexed author, uint256 reserveCredit, uint64 buyerCooldownUntil)",
  "event PaidPurchaseReportFinalized(uint64 indexed reportId, address indexed author, address indexed buyer, uint256 buyerEntitlement, uint256 buyerCredit, uint256 reserveCredit, uint64 claimDeadline)",
  "event PaidPurchaseReportCreditClaimed(uint64 indexed reportId, address indexed buyer, uint256 amount)",
  "event PaidPurchaseReportCreditExpired(uint64 indexed reportId, uint256 reserveCredit)",
  "event RestitutionReserveClaimed(address indexed recipient, uint256 amount)",
  "error AlreadyRegistered()",
  "error BadEconomics()",
  "error DisputeLocked()",
  "error ListingNotFound()",
  "error PaidPurchaseReportNotFound()",
  "error PaidPurchaseReportInvalidState()",
  "error PaidPurchaseReceiptIneligible()",
  "error PaidPurchaseReceiptConsumed()",
  "error PaidPurchaseBuyerBusy()",
  "error PaidPurchaseListingBusy()",
  "error PaidPurchaseAuthorBusy()",
  "error PaidPurchaseBuyerCooldown()",
  "error PaidPurchaseAuthorCooldown()",
  "error PaidPurchaseReviewExpired()",
  "error PaidPurchaseReviewOpen()",
  "error PaidPurchaseEvidenceTooLong()",
  "error PaidPurchaseSlashPageTooLarge()",
  "error PaidPurchaseSlashSnapshotIncomplete()",
  "error PaidPurchaseCreditNotFunded()",
  "error PaidPurchaseCreditExpired()",
  "error PaidPurchaseCreditOpen()",
  "error PaidPurchaseCreditAlreadyHandled()",
  "error PurchaseLaneIneligible()",
]);
